# Generated by Django 4.1.3 on 2022-11-29 01:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ciudades/fotos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudades.ciudad')),
            ],
        ),
    ]
