# Generated by Django 4.1.3 on 2022-12-01 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciudades', '0002_alter_city_options_city_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='likes',
        ),
        migrations.AddField(
            model_name='city',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
